export const REGISTER_TOKEN_START = "REGISTER_TOKEN_START";
export const REGISTER_TOKEN_SUCCESS = "REGISTER_TOKEN_SUCCESS";
export const REGISTER_TOKEN_FAILED = "REGISTER_TOKEN_FAILED";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";