# Generated by Django 2.1.3 on 2020-05-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
